Python/Django/Level_2/dashboard/apps/admin_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^create_user$', views.create_user, name="create_user"),
	url(r'^remove/(?P<id>\d+)$', views.remove, name="remove"),
]

Python/Django/Level_2/dashboard/apps/message_app/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create/(?P<id>\d+)$', views.create, name='create'),
	url(r'^comment/(?P<id>\d+)$', views.comment, name='comment'),
]

Python/Django/Level_2/dashboard/apps/user_app/urls.py
from django.conf.urls import url 
from . import views

app_name = 'user_app'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^loginpage$', views.loginpage, name='loginpage'),
	url(r'^login$', views.login, name='login'),
	url(r'^registration$', views.registration, name='registration'),
	url(r'^register$', views.register, name='register'),
	url(r'^logout$', views.logout, name='logout'),
	###
	url(r'^userinfo/(?P<id>\d+)$', views.userinfo, name='userinfo'),
	url(r'^dashboard$', views.dashboard, name='dashboard'),
	url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
	###
	url(r'^update_information/(?P<id>\d+)$', views.update_information, name='update_information'),
	url(r'^update_password/(?P<id>\d+)$', views.update_password, name='update_password'),
	url(r'^update_description/(?P<id>\d+)$', views.update_description, name='update_description'),
]

Python/Django/Level_2/dashboard/dashboard/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace='user_app')),
    url(r'^message_app/', include('apps.message_app.urls', namespace='message_app')),
    url(r'^admin_app/', include('apps.admin_app.urls', namespace='admin_app')),
]

Python/Django/Level_2/dashboard/apps/user_app/models.py
from __future__ import unicode_literals
import bcrypt

from django.db import models

# Create your models here.
class UserManager(models.Manager):

	def create_user(self, email, first_name, last_name, password, description):
		user = self.create(email=email, first_name=first_name, last_name=last_name, password=password, description=description)
		return user

	def hash_password(self, password):
		pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
		return pw_hash

	def compare_passwords(self, user, password):
		hashed = user.password.encode()
		if bcrypt.hashpw(password.encode(), hashed) == hashed:
			return True
		else:
			return False

	def validate_and_add(self, data):
		errors = []
		if len(data['email'])<1:
			errors.append('EMAIL FIELD CANNOT BE LEFT EMPTY.')
		if len(data['first_name'])<1:
			errors.append('FIRST NAME CANNOT BE LEFT BLANK.')
		if len(data['last_name'])<1:
			errors.append('LAST NAME CANNOT BE LEFT BLANK.')
		if len(data['password'])<1:
			errors.append('PASSWORD FIELD CANNOT BE LEFT EMPTY.')
		if errors:
			return (False, errors)
		try:
			self.get(email=data['email'])
			errors.append('It appears as though this email already exists in the database.')
			return (False, errors)
		except:
			password = self.hash_password(data['password'])
			user = self.create_user(data['email'], data['first_name'], data['last_name'], password, data['description'])
			return (True, user)

	def login(self, data):
		password = data['password']
		errors = []
		try:
			user = self.get(email=data['email'])
			if self.compare_passwords(user, password):
				return (True, user)
			else:
				errors.append('Password does not match email in database.')
				return (False, errors)
		except:
			errors.append('It appears as though this email does not yet exist in the database.')
		return (False, errors)

	def update_information(self, data, id):
		user = self.filter(id=id)
		if data['email']:
			user.update(email=data['email'])
		if data['first_name']:
			user.update(first_name=data['first_name'])
		if data['last_name']:
			user.update(last_name=data['last_name'])
		return True

	def update_password(self, data, id):
		errors=[]
		if data['password'] != data['confirm_password']:
			errors.append('password must match password confirmation')
			return (False, errors)
		else:
			hashed = self.hash_password(data['password'])
			self.update(password=hashed)
			return True

	def update_description(self, description, id):
		user = self.filter(id=id)
		user.update(description=description)
		return True

class User(models.Model):
	email = models.CharField(max_length=255)
	first_name = models.CharField(max_length=45)
	last_name = models.CharField(max_length=45)
	password = models.CharField(max_length=255)
	description = models.CharField(max_length=4000)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	objects = UserManager()

Python/Django/Level_2/dashboard/apps/user_app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User
from ..message_app.models import Message

# Create your views here.
def index(request):
	if 'first_name' in request.session:
		return redirect(reverse('user_app:dashboard'))
	else:
		return render(request, 'user_app/welcome.html')

def loginpage(request):
	if 'first_name' in request.session:
		return redirect(reverse('user_app:dashboard'))
	return render(request, 'user_app/login.html')

def login(request):
	valid, res = User.objects.login(request.POST)
	if valid:
		user = User.objects.get(email = request.POST['email'])
		request.session['first_name'] = user.first_name
		request.session['id'] = user.id
		return redirect(reverse('user_app:dashboard'))
	else:
		for error in res:
			messages.error(request, error)
	return redirect(reverse('user_app:loginpage'))

def registration(request):
	if 'first_name' in request.session:
		return redirect(reverse('user_app:dashboard'))
	return render(request, 'user_app/register.html')

def register(request):
	errors = []
	valid, res = User.objects.validate_and_add(request.POST)
	if valid:
		user = User.objects.get(email = request.POST['email'])
		request.session['first_name'] = user.first_name
		request.session['id'] = user.id
		return redirect(reverse('user_app:dashboard'))
	else:
		for error in res:
			messages.error(request, error)
		return redirect(reverse('user_app:registration'))

def logout(request):
	request.session.clear()
	return redirect(reverse('user_app:index'))

#####

def dashboard(request):
	if 'first_name' not in request.session:
		return redirect(reverse('user_app:index'))
	context = {
		'users': User.objects.all()
	}
	return render(request, 'user_app/dashboard.html', context)

def edit(request, id):
	context = {
		'user': User.objects.get(id=id)
	}
	return render(request, 'user_app/edit.html', context)

def update_information(request, id):
	User.objects.update_information(request.POST, id)
	return redirect(reverse('user_app:userinfo', kwargs={'id':id}))

def update_password(request, id):
	User.objects.update_password(request.POST, id)
	return redirect(reverse('user_app:userinfo', kwargs={'id':id}))

def update_description(request, id):
	User.objects.update_description(request.POST['description'], id)
	return redirect(reverse('user_app:userinfo', kwargs={'id':id}))

def userinfo(request, id):
	user = User.objects.get(id=id)
	context = {
		'user': user,
		'usermessages': Message.objects.filter(to_user=user.id).order_by('-created_at'),
	}
	print Message.objects.all()
	return render(request, 'user_app/user.html', context)

Python/Django/Level_2/dashboard/apps/user_app/templates/user_app/dashboard.html
<html>
<head>
	<title>The DashBoard | DashBoard</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'user_app/dashboard.css' %}" media="screen" title="no title"  charset="utf-8">

	<script type="text/javascript" src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script type="text/javascript" src = "https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
 	<script type="text/javascript">
    	$(document).ready(function(){
    		$('.grid').masonry({
			itemSelector: '.grid-item',
			
			horizontalOrder: true
      });

    })
  </script>

</head>
<body>
	<h1>D A S H B O A R D</h1>
	<hr>

	<div id = "main">
		<h3>Welcome, {{request.session.first_name}}
			{% if request.session.id == 1 %}
				(Admin)
			{% endif %}
		</h3>
		<a href="{% url 'user_app:logout' %}" id = "logout">Log Out</a>
		<h3>List of All Users:</h3>
		<hr>
		{% if request.session.id == 1 %}
			<a href="{% url 'admin_app:index' %}">Add New</a>
		{% endif %}
		<br>
		<br>

			<div class = 'grid'>

				{% for user in users %}
					<div class = "grid-item">

						<a href = "{% url 'user_app:userinfo' id=user.id %}">{{user.first_name}} {{user.last_name}}</a>
						<br>
						 <div id = "italic">Initiated on {{user.created_at}}</div>
		
						 <div id = "description">{{user.description}}</div>
						 <br>
						{% if user.id == request.session.id or request.session.id == 1 %}
							<a href="{% url 'user_app:edit' id=user.id %}">Edit</a>
						{% endif %}
						{% if request.session.id == 1 %}
							{% if user.id != request.session.id %}
								<a href="{% url 'admin_app:remove' id=user.id %}">Remove</a>
							{% endif %}
						{% endif %}

					</div>
					
				{% endfor %}
			</div>

	</div>
</body>
</html>

Python/Django/Level_2/dashboard/apps/user_app/templates/user_app/edit.html
<html>
<head>
	<title>{{user.first_name}} {{user.last_name}} - Edit Profile | DashBoard</title>
</head>
<body>
	<a href="{% url 'user_app:dashboard' %}">Home</a>
	<h4>{{user.first_name}} {{user.last_name}}</h4>
	<a href="{% url 'user_app:logout' %}">Log Out</a>
	<h3>Edit Profile</h3>
	<p>Edit Information</p>
	<form action = "{% url 'user_app:update_information' id=user.id %}" method='post'>
		{% csrf_token %}
		<input type = 'email' name = 'email' placeholder = 'Change Email'><br>
		<input type = 'text' name = 'first_name' placeholder = 'Change First Name'><br>
		<input type = 'text' name = 'last_name' placeholder = 'Change Last Name'><br>
		<input type = 'submit' value = 'Save'>
	</form>

	<p>Change Password</p>
	<form action = "{% url 'user_app:update_password' id=user.id %}" method='post'>
		{% csrf_token %}
		<input type = 'password' name = 'password' placeholder = 'New Password'><br>
		<input type = 'password' name = 'confirm_password' placeholder = 'Confirm New Password'><br>
		<input type = 'submit' value = 'Update Password'>
	</form>

	<p>Edit Description</p>
	<form action = "{% url 'user_app:update_description' id=user.id %}" method="post">
		{% csrf_token %}
		<textarea placeholder='{{user.description}}' name = 'description'></textarea><br>
		<input type = 'submit' value = 'Save'>
	</form>
</body>
</html>

Python/Django/Level_2/dashboard/apps/user_app/templates/user_app/login.html
<html>
<head>
	<title>DashBoard | Log In</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'user_app/login.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>

	<header>
		<h1>D A S H B O A R D</h1>
		<hr>
	</header>

	<div id = "login">

		<h3>Log In:</h3>
		{% for message in messages %}
			{{message}}
		{% endfor %}
		<form action = "{% url 'user_app:login' %}" method='post'>
			{% csrf_token %}
			<input type = 'email' name = 'email' placeholder = 'email'><br>
			<input type = 'password' name = 'password' placeholder = 'password'><br>
			<input type = 'submit' value = 'Log In' id = 'loginhere'>
		</form>
	</div>

	<p>Don't have an account? <a href="{% url 'user_app:registration' %}">Click here to register</a>.</p>

</body>
</html>

Python/Django/Level_2/dashboard/apps/user_app/templates/user_app/register.html
<html>
<head>
	<title>DashBoard | Register</title>
	<header>
		<h1>D A S H B O A R D</h1>
		<hr>
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'user_app/register.css' %}" media="screen" title="no title"  charset="utf-8">
	</header>
</head>
<body>
	<div id = "register">
	<h3>REGISTER:</h3>
		<form action = "{% url 'user_app:register' %}" method='post'>
			{% csrf_token %}
			<input type = 'email' name = 'email' placeholder = 'Email Address'><br>
			<input type = 'text' name = 'first_name' placeholder = 'First Name'><br>
			<input type = 'text' name = 'last_name' placeholder = 'Last Name'><br>
			<textarea rows="4" cols="19.5" name = 'description' placeholder="Describe yourself"></textarea><br>
			<input type = 'password' name = 'password' placeholder = 'Password'><br>
			<input type = 'password' name = 'confirm_password' placeholder = 'Confirm Password'><br>
			<input id = "registerhere" type = 'submit' value = 'Register'>
		</form>

	</div>

	<p>Already have an account? <a href="{% url 'user_app:loginpage' %}">Click Here to Login</a>. </p>
</body>
</html>

Python/Django/Level_2/dashboard/apps/user_app/templates/user_app/user.html
<html>
<head>
	<title>User | DashBoard</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'user_app/user.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>

		<h1>D A S H B O A R D</h1>
		<hr>
	<div id = "main">
		
		<a href="{% url 'user_app:dashboard' %}" id = "home">Home</a>
		<a href="{% url 'user_app:logout' %}" id = "logout">Log Out</a>

		<h3>{{user.first_name}} {{user.last_name}}</h3>
		<p>Registered at: {{user.created_at}}</p>
		<p>User ID: {{user.id}}</p>
		<p>Email address: {{user.email}}</p>
		<p>Description: {{user.description}}</p>
		{% if user.id == request.session.id %}
			<a href="{% url 'user_app:edit' id=user.id %}">Edit</a>
		{% endif %}

		{% if request.session.id == user.id %}
		<h4>Leave a message for your friends.</h4>
		{% else %}
		<h4>Leave a message for {{user.first_name}}</h4>
		{% endif %}
		{% for message in messages %}
			{{message}}
		{% endfor %}
		{{request.session.first_name}}:
		<form action = "{% url 'message_app:create' id=request.session.id %}" method='post'>
			{% csrf_token %}
			<textarea rows="5" cols="30" name = 'message'></textarea>
			<input type = 'hidden' name = 'to_user' value = '{{user.id}}'>
			<input id = "posting" type = 'submit'>
		</form>

		<h4>Messages:</h4>

		{% for message in usermessages %}
			{{message.user.first_name}} says:
			<br>
			{{message.message}}
			<br>
			COMMENTS:
			<br>
			{% for comment in message.comment.all %}
				{{comment.user.first_name}}:
				{{comment.comment}}
				<br>
			{% empty %}
				<p>No comments yet!</p>
			{% endfor %}
		<br>
		{{request.session.first_name}}:
		<form action = "{% url 'message_app:comment' id=request.session.id %}" method='post'>
			{% csrf_token %}
			<input type = 'text' name = 'comment' placeholder='Post a comment'>
			<input type = 'hidden' name = 'message' value = '{{message.id}}'>
			<input class = 'posting' type = 'submit' value='Comment'>
		</form>
		{% empty %}
			<p>No messages yet</p>
		{% endfor %}

	</div>
</body>
</html>

Python/Django/Level_2/dashboard/apps/user_app/templates/user_app/welcome.html
<html>
<head>
	<title>DashBoard | Home Page</title>
	{% load staticfiles %}<link rel="stylesheet" href="{% static 'user_app/welcome.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
	<header>
		<h1>D A S H B O A R D</h1>
		<hr>
	</header>

	<div id = "welcomeblock">
		<h2>Welcome</h2>
		<p>This is an application built using an MVC framework (MTV framework in Django terms, of course).</p>
		<h3><a href="{% url 'user_app:loginpage' %}">Start</a><h3>
	</div>

	<br>
	<div id = "manage">
		<h4>✓ Admin Functionality</h4>
		<p>This application allows admin to add, edit, and remove users.</p>
		<h4>✓ Leave Messages</h4>
		<p>Users will be able to leave messages to each other using this application.</p>
		<h4>✓ Edit User Information</h4>
		<p>Admins will be able to edit another user's information (email address, first name, last name, etc).</p>
	</div>
</body>
</html>