Python/Django/Level_2/interests/apps/interests_app/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^users$', views.users, name='users'),
	url(r'^add$', views.add, name='add'),
	url(r'^show(?P<id>\d+)$', views.show, name='show'),
]

Python/Django/Level_2/interests/interests/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.interests_app.urls', namespace='interests')),
]

Python/Django/Level_2/interests/apps/interests_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Interest(models.Model):
	interest = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.interest

####

class UserManager(models.Manager):

	def create_user(self, name):
		user = self.create(name=name)
		user.save()
		return user

	def validate_user(self, data):
		errors = []
		if len(data['name'])<2:
			errors.append('Please input a name with a minimum length of two characters.')
		if len(data['interest'])<5:
			errors.append('Please input an interest with a minimum length of five characters.')
		if len(data['name'])>255:
			errors.append('Name is too long! Please make sure your name is less than 255 characters in length.')
		if len(data['interest'])>255:
			errors.append('Interest field is too long! Please make sure your interest is less than 255 characters long.')
		if errors:
			return (False, errors)
		else:
			this_interest = Interest(interest=data['interest'])
			this_interest.save()
			try:
				self.get(name=data['name'])
				user = User.objects.get(name=data['name'])	
			except:
				user = User(name=data['name'])
				user.save()
			user.user_interests.add(this_interest)
			print user.user_interests.all()
			return (True, user)

class User(models.Model):
	name = models.CharField(max_length=255)
	user_interests = models.ManyToManyField(Interest, related_name="interests_of_users")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

	def __unicode__(self):
		return self.name

Python/Django/Level_2/interests/apps/interests_app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import User, Interest
from django.contrib import messages

# Create your views here.
def index(request):
	return render(request, 'interests_app/index.html')

def add(request):
	valid, res = User.objects.validate_user(request.POST)
	if valid:
		return redirect(reverse('interests:users'))
	else:
		for error in res:
			messages.error(request, error)
		return redirect(reverse('interests:index'))


def users(request):
	context = {
		'users':User.objects.all(),
		'interests': Interest.objects.all()
	}
	return render(request, 'interests_app/users.html', context)

def show(request, id):
	context = {
		'user': User.objects.get(id=id)
	}
	return render(request, 'interests_app/show.html', context)

Python/Django/Level_2/interests/apps/interests_app/templates/interests_app/index.html
<html>
<head>
	<title>User Interests</title>
</head>
<body>
	{% if messages %}
		{% for message in messages %}
			{{message}}
		{% endfor %}
	{% endif %}
	<form action = "{% url 'interests:add' %}" method="post"> 
		{% csrf_token %}
		<input type = 'text' name = 'name' placeholder = 'Name'><br>
		<input type = 'text' name = 'interest' placeholder = 'Interest'><br>
		<input type = 'submit' value ='Submit'>
	</form>
	<a href="{% url 'interests:users' %}">Home</a>
</body>
</html>

Python/Django/Level_2/interests/apps/interests_app/templates/interests_app/show.html
<html>
<head>
	<title>User Interests</title>
</head>
<body>
	<h1>User's Interests</h1>
		{{user.name}}<br>
		{% for interest in user.user_interests.filter %}
		 	{{interest}}<br>
		 {% endfor %}
	<a href="{% url 'interests:users' %}">Back to Users</a><br>
	<a href="{% url 'interests:index' %}">Enter another user interest</a>
</body>
</html>

Python/Django/Level_2/interests/apps/interests_app/templates/interests_app/users.html
<html>
<head>
	<title>User Interests</title>
</head>
<body>
	{% for user in users %}
		{{user.name}}
		 <a href="{% url 'interests:show' id=user.id %}">View</a>
		<br>
	{% endfor %}

	<a href="{% url 'interests:index' %}">Enter another user interest</a>
</body>
</html>