Python/Django/Level_2/selftest/apps/selftestloginreg/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^login$', views.login, name='login'),
	url(r'^register$', views.register, name='register'),
	url(r'^success$', views.success, name='success'),
	url(r'^logout$', views.logout, name='logout'),
]

Python/Django/Level_2/selftest/selftest/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.selftestloginreg.urls', namespace = 'selftestloginreg')),
]

Python/Django/Level_2/selftest/apps/selftestloginreg/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt

# Create your models here.
class UserManager(models.Manager):

	def hash_password(self, password):
		hashed_pw = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
		print hashed_pw
		return hashed_pw

	def check_passwords(self, user, password):
		if bcrypt.hashpw(password.encode(), user.password.encode()) == user.password.encode():
			return True
		else:
			return False

	def create_user(self, data):
		hashedpw = self.hash_password(data['password'])
		user = self.create(email = data['email'], password = hashedpw)
		print user.email
		return user

	def validate_and_create(self, data):
		errors = []
		if len(data['email'])<1:
			errors.append('You must include an email in order to register.')
		if len(data['password'])<8:
			errors.append('Password must be at least eight characters.')
		if data['password'] != data['confirm_password']:
			errors.append('Password must match password confirmation.')
		else:
			try:
				self.get(email=data['email'])
				errors.append('Whoops! Looks like this email already exists in the database.')
				return (False, errors)
			except:
				user = self.create_user(data)
				return (True, user)
		if errors:
			return (False, errors)

	def login(self, data):
		errors = []
		if len(data['email'])<1:
			errors.append('You must include an email in order to log in.')
		if len(data['password'])<1:
			errors.append('You must include a password in order to log in.')
		else:
			try:
				user = self.get(email=data['email'])
				if self.check_passwords(user, data['password']):
					return (True, user)
			except:
				errors.append('Incorrect email or password')
		if errors:
			return (False, errors)

class User(models.Model):
	email = models.CharField(max_length=45)
	password = models.CharField(max_length=45)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

Python/Django/Level_2/selftest/apps/selftestloginreg/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import User
from django.contrib import messages

# Create your views here.
def index(request):
	return render(request, 'selftestloginreg/index.html')

def login(request):
	valid, res = User.objects.login(request.POST)
	if valid:
		request.session['email'] = request.POST['email']
		request.session['statement'] = 'Welcome back to the site.'
		return redirect(reverse('selftestloginreg:success'))
	else:
		for error in res:
			messages.error(request, error)
		return redirect(reverse('selftestloginreg:index'))

def register(request):
	valid, res = User.objects.validate_and_create(request.POST)
	if valid:
		request.session['email'] = request.POST['email']
		request.session['statement'] = 'Thank you for registering! Welcome to the site.'
		return redirect(reverse('selftestloginreg:success'))
	else:
		for error in res:
			messages.error(request, error)
		return redirect(reverse('selftestloginreg:index'))

def success(request):
	context = {
		'users': User.objects.all()
	}
	return render(request, 'selftestloginreg/success.html', context)

def logout(request):
	request.session.clear()
	return redirect(reverse('selftestloginreg:index'))
	

Python/Django/Level_2/selftest/apps/selftestloginreg/templates/selftestloginreg/index.html
<html>
<head>
	<title>LOGIN PAGE</title>
</head>
<body>
	<p>LOG IN:</p>
	<form action = "{% url 'selftestloginreg:login' %}" method = 'post'>
		{% csrf_token %}
		<input type = 'email' name='email' placeholder='email'>
		<input type = 'password' name='password' placeholder='password'>
		<input type = 'submit' value = 'Log In'>
	</form>

	{% for message in messages %}
		{{message}}
	{% endfor %}

	<p>CREATE AN ACCOUNT:</p>
	<form action = "{% url 'selftestloginreg:register' %}" method = 'post'>
		{% csrf_token %}
		<input type = 'email' name='email' placeholder = 'email'><br>
		<input type = 'password' name='password' placeholder = 'password'><br>
		<input type = 'password' name='confirm_password' placeholder = 'confirm_password'><br>
		<input type = 'submit' value = 'Create Account'>
	</form>
</body>
</html>

Python/Django/Level_2/selftest/apps/selftestloginreg/templates/selftestloginreg/success.html
<html>
<head>
	<title>SUCCESS PAGE</title>
</head>
<body>
	<p>Welcome to the success page, {{request.session.email}}! {{request.session.statement}}</p>
	<p>Other users' emails:</p>
	{% for user in users %}
		{% if user.email != request.session.email %}
			{{user.email}}
			<br>
		{% endif %}
	{% endfor %}
	<br>
	<form action = "{% url 'selftestloginreg:logout' %}" method = 'post'>
		{% csrf_token %}
		<input type = 'submit' value = 'Log Out'>
	</form>
</body>
</html>